### ISSUE TITLE
PHP Warning:  Undefined property: Creame\MOCache\MOFile::$entries

### ISSUE THREAD

**Issue by redburn** [colinleroy/wp-native-gettext#4]
After installing this plugin, the error log is filling up with two types of errors:

- Undefined property: Creame\MOCache\MOFile::$entries in /home/example.com/public_html/wp-content/plugins/native-gettext/classes/class-native-mo.php on line 83; 
- foreach() argument must be of type array|object, null given in /home/example.com/public_html/wp-content/plugins/native-gettext/classes/class-native-mo.php on line 83"

Version 1.1.3 on WordPress 6.4.5 with PHP 8.3.

**Comment by colinleroy** [comment]
Hi,
it looks like an issue with another plugin that maybe handles translations. Can you try and see, by disabling plugins one by one, which one it is? that way I'll be able to reproduce.
